### PR TITLE
Schematron validation

### PR DESCRIPTION
**Pull request by bpark1327**
## Pull Request Description

Replace custom validation.rb files with Schematron.

## Checklist

Not all may apply:

- [x] OS-HPXML git subtree has been pulled
- [x] 301 ruleset and unit tests have been updated
- [x] 301validator.rb has been updated (reference EPvalidator.rb)
- [x] Workflow tests have been updated
- [x] Documentation has been updated
- [x] `openstudio tasks.rb update_measures` has been run
- [x] No unexpected regression test changes on CI

### CODE REVIEW

**Comment by bpark1327** [comment]
It looks like test_validation.rb is failing when it adds `/HPXML/Building/BuildingDetails/Enclosure/Attics/Attic` (i.e. there are two attics). And it triggers the assert in `[UnventedAttic]`. I guess Schematron expects `../../Attics/Attic[AtticType/Attic[Vented="false"]]/WithinInfiltrationVolume` to be 1, which it seems to be an expected behavior. 
I guess we need an exception for this case. We need to add this exception in _get_expected_error_msg. 
Or, maybe we need to test the expected error message doesn't exist in error messages?!

**Comment by shorowit** [comment]
> 
> 
> It looks like test_validation.rb is failing when it adds `/HPXML/Building/BuildingDetails/Enclosure/Attics/Attic` (i.e. there are two attics). And it triggers the assert in `[UnventedAttic]` pattern. I guess Schematron expects `../../Attics/Attic[AtticType/Attic[Vented="false"]]/WithinInfiltrationVolume` to be 1, and returning an error message.
> But, `count(h:Building/h:BuildingDetails/h:Enclosure/h:Roofs/h:Roof) &gt;= 0` expects no error message and this conflict fails the test.
> Maybe we should check the expected error message doesn't exist (when assertion starts with 0 or more) rather than expecting the error message to be empty?! Because in some cases, adding an element may or may not trigger unintended(?) error messages.
> Hope it makes sense to you.

Good idea, thanks for the idea. I will try that.

**Review by shorowit — APPROVED** [review]
This looks really good. Will let the CI do one more pass on it and will verify the CI results before merging.

**Comment by shorowit** [comment]
Thanks @bpark1327!

**Pull request merged**
